// <auto-generated />
namespace B05ASPC02_w01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class annt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(annt));
        
        string IMigrationMetadata.Id
        {
            get { return "202408111000106_annt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
